org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# parchment_minecraft_version=1.21.1
# parchment_mappings_version=2024.11.17
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.53-beta
loader_version_range=[1,)

## Mod Properties
mod_id=generalmechanics
mod_name=General Mechanics
mod_license=APGPLv3
mod_version=0.0.1-PRE-ALPHA
mod_group_id=general.mechanics
mod_authors=iso2t
mod_description=The technology mod.

## Integrations
jei_version=29.6.2.31
